### ISSUE TITLE
User Manager: show the date of the last password reset

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#105]
Add a new field to the users table last_reset_date to store the date of the last password reset (existing password_reset_date field indicates when password will expire)

**Comment by ddelvecchio** [comment]
Added appropriate DDL to the Data_Schema_upgrade.setup to create the field.  
Added appropriate mapping to User.hmb.xml hibernate configuration file.
Added new field to User model object.
Set new field in appropriate places to make sure date is set correctly.
