### ISSUE TITLE
implement stronger password requirements

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#106]
Requirements
---

Must not contain your username or any part of your full name that exceeds two characters (Example: cannot be 'SMI' if your last name is 'SMITH').

Must be different from current password

Password length must be a minimum of 12 characters

and contain characters from 3 of the following 4 categories:

- At least 1 digit (0-9)

- At least 1 symbol (~, !, @, #, $, %, =, +, <, >, /, ?)

- At least 1 UPPERCASE English letter (A-Z)

- At least 1 lowercase English letters (a-z)

**Comment by ddelvecchio** [comment]
Added additional password requirements in the setPassword method for the User model class.  This is where the existing code contained password validation logic.
