### ISSUE TITLE
consolidate EMF documentation

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#13]
EPA installation guide
https://www.cmascenter.org/emf/install/

Main EMF user's guide (includes MARAMA installation instructions)
https://www.cmascenter.org/emf/internal/guide.html

CoST user's guide (includes all-in-one installation instructions)
https://www.cmascenter.org/cost/documentation/2.12/html/

SQL Basics for the EMF
https://www.cmascenter.org/emf/internal/sql_basics.html

Temporal Allocation Using the EMF
https://www.cmascenter.org/emf/internal/temporal_allocation.html

Inventory Projection Using the EMF
https://www.cmascenter.org/emf/internal/inventory_projection.html

SMOKE-MOVES and the EMF (has info about case management)
https://www.cmascenter.org/emf/internal/smoke_moves/

**Comment by CMASCenter** [comment]
For CoST I don't think we need to include all of this other EMF documentation.  I can see creating a CoST documentation landing page that has links to the User's Guide/Training manual, Equations Doc, EMF SQL Primer, CMDB document...and this is already available on the EPA CoST page, with the exception of the SQL primer. 

For the User's Guide, do you think that I need to update the screen shots with images from the current version of the software?  For example, I'm seeing that the screen shots in the manual include some measures that are no longer available in the current CMDB.  As long as these defunct measures are not being used in an example exercise, i.e., they just exist in the screen shot of a list of measures, I don't think we need to spend time updating the image.

**Comment by cseppan** [comment]
The latest version of the EMF User's Guide removes the MARAMA-specific installation instructions, and adds in chapters on Case Management, Temporal Allocation, and Inventory Projection.

https://www.cmascenter.org/cost/documentation/3.1/EMF%20User's%20Guide/

The guide has been converted to Markdown and added to the Git repository: https://github.com/USEPA-OAQPS/emf/tree/master/EMF/deploy/doc/guides

The CoST User's Guide has also been converted to Markdown and added to the Git repository: https://github.com/USEPA-OAQPS/emf/tree/master/EMF/deploy/doc/guides/cost

Since the SQL Basics guide isn't version-specific, it's linked from the main CoST/EMF page on the CMAS site

https://www.cmascenter.org/cost/sql_basics.html

It's also in the Git repository: https://github.com/USEPA-OAQPS/emf/blob/master/EMF/deploy/doc/guides/sql_basics.md

All documents are converted from Markdown to HTML (and PDF for the CoST guide) using Pandoc.
