### ISSUE TITLE
button mnemonic conflict / remove Edit from Revisions tab in view mode?

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#66]
When viewing a dataset's properties, the Revisions tab has an Edit button. The mnemonic for this button (E) conflicts with the Edit Properties button that's part of the window. 'I' or 'T' are available for changing the mnemonic, but should this Edit button be here at all?

**Comment by eyth** [comment]
Isn't this for editing a revision?  Yes we could call it something else if
needed.

**Comment by cseppan** [comment]
Specifically, this is a problem when viewing the dataset's properties, not editing. All the other tabs don't have the Add or Edit buttons when you're only viewing.

**Comment by eyth** [comment]
Oh right - thanks for clarifying...  Agreed it shouldn't be Edit from the
View properties window

**Comment by cseppan** [comment]
Commit ce9571d8f24d42cca08c3f44f5123ca947ea16fd removes the Edit button when the Revisions tab is displayed in the Dataset Properties Viewer window. The Revisions Edit button is still available in the Dataset Properties Editor window.
