### ISSUE TITLE
View/Edit QA Step: disabled checkboxes aren't accessible

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#70]
The View QA Step window (ViewQAStepWindow.java) and the Edit QA Step window (EditQAStepWindow.java) use disabled checkboxes to show "Arguments same as template?" and "Current Output?" status fields. These disabled checkboxes aren't part of the focus loop, so they can't be tabbed through or read by the screen reader. Switching to using focusable Label widgets with Yes/No values seems like a good fix.

The Required? checkbox is disabled if the QA Step has been marked as required. For the View QA Step window, this can also be a focusable Label with Yes/No. For the Edit window, it needs to be a functional checkbox if the QA step isn't already required.

**Comment by ddelvecchio** [comment]
Ended up using Label objects as you recommended
